import type { Metadata } from "next";
import localFont from "next/font/local";
import { Poppins } from "next/font/google";

import "./globals.css";
import ToastProvider from "@/components/ToastProvider";

const peyda = localFont({
  src: [
    {
      path: "../public/fonts/PeydaFaNum-Black.ttf",
      weight: "900",
    },
    {
      path: "../public/fonts/PeydaFaNum-ExtraBold.ttf",
      weight: "800",
    },
    {
      path: "../public/fonts/PeydaFaNum-Bold.ttf",
      weight: "700",
    },
    {
      path: "../public/fonts/PeydaFaNum-SemiBold.ttf",
      weight: "600",
    },
    {
      path: "../public/fonts/PeydaFaNum-Medium.ttf",
      weight: "500",
    },
    {
      path: "../public/fonts/PeydaFaNum-Regular.ttf",
      weight: "400",
    },
    {
      path: "../public/fonts/PeydaFaNum-Light.ttf",
      weight: "300",
    },
    {
      path: "../public/fonts/PeydaFaNum-ExtraLight.ttf",
      weight: "200",
    },
    {
      path: "../public/fonts/PeydaFaNum-Thin.ttf",
      weight: "100",
    },
  ],
  variable: "--font-peyda",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Online Services",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body
        dir="rtl"
        className={`${peyda.variable} ${poppins.variable} antialiased`}
      >
        {children}
        <ToastProvider />
      </body>
    </html>
  );
}
